skip_docs
require 'Pony'

platform :ios do
	
	desc "load ios specific env"
	before_all do
		Dotenv.load ".ios.env"
		if is_ci
			puts 'runing in ci/cd pipeline'
		else
			puts 'running for local system and loading secret env'
			Dotenv.overload('.env', '.secret.env')
		end
	end

	desc "Sync signing"
	private_lane :signing do
		setup_ci if is_ci
		# create CERT_FILE_PATH,CERT_CERTIFICATE_ID
		cert #get_certificates 
		echo lane_context[SharedValues::CERT_FILE_PATH]
		echo lane_context[SharedValues::CERT_CERTIFICATE_ID]
		# sigh
		#update_code_signing_settings(profile_name: mapping['MATCH_APP_IDENTIFIER'])
	end

	desc "Build ios app"
	lane :build do
		signing if is_ci
		gym #build_ios_app
	end
	
	desc "Upload ipa to diawi"
	lane :upload do
		build
		ensure_env_vars(env_vars: ['DIAWI_TOKEN']) if is_ci
		ENV['DIAWI_TOKEN'] = prompt(text: 'Enter DIAWI TOKEN: ') if not(ENV['DIAWI_TOKEN'])
		diawi(file: lane_context[SharedValues::IPA_OUTPUT_PATH])
		sh("rm","-R","./../build/ios")
		share
	end

	desc "mail"
	private_lane :share  do
		download_url = lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI]
		
		from = ENV['SEND_E_MAIL_USERNAME']
		to = ENV['SEND_E_MAIL_TO']
		subject = ENV['SEND_E_MAIL_SUBJECT']
		password = ENV['SEND_E_MAIL_PASSWORD']
		image_url = ENV['SEND_E_MAIL_APP_ICON_URL']
		title = ENV['SEND_E_MAIL_APP_TITLE']
		sub_title = ENV['SEND_E_MAIL_APP_SUB_TITLE']
		primary_color = ENV['SEND_E_MAIL_APP_PRIMARY_COLOR']
		version = "build #{get_build_number}, version #{get_version_number}"

		body = html_mail image_url,title,sub_title,version,download_url,primary_color
		send_mail from,to,subject,body,password
	end
end
	
def send_mail(from,to,sub,content,password)
	Pony.mail(:to =>to,	:from => from, :subject => sub,:headers => { 'Content-Type' => 'text/html; charset=UTF-8' },:body => content,:via => :smtp, :via_options => {
			:address        => 'smtp.gmail.com',
			:port           => '587',
			:user_name      => from,
			:password       => password,
			:authentication => :plain,
			:domain         => "gmail.com"
	})
end
	
def html_mail(image_url,title,sub_title,version,download_url,primary_color)
	
	return 	"<div style='background: #e9f0f4; padding: 80px;'>
		<div style='margin: auto; height: auto;width: 400px; background: #fff;border-radius: 16px; padding-bottom:20px; '>
				<img style='width:90%;height: auto; border-style: none;margin: 24px; max-height: 350px;'
				src='#{image_url}' />
				<img style='width: 100%;' src='https://drive.google.com/uc?export=view&id=1bHYj51poOV3mkwywwB4_9dqTNitZlgYo' width='100%'>
				<table style='padding:16px; padding-bottom:8px;'  width= '100%;margin:0;border-collapse: collapse; ' cellspacing= '0' cellpadding= '0'>
					<tbody>
					<tr><td><span style='font-size: 1.75rem;font-weight: 800;line-height: 2.25rem;'>#{title}</span></td></tr>
					<tr><td><span style='font-size: 1.25rem;line-height: 2rem;'>#{sub_title}</span></td></tr>
					<tr><td><span style='font-size: .8rem;line-height: 1rem;'>#{version}</span></td></tr>
					<tr style='text-align:center;'><td><a href='#{download_url}'style='color:#{primary_color}' >Click here to download</a></td></tr>
					</tbody>
				</table>	
			</div>    
	</div>"
end
	